// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zefmabelixpuaelpivjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplZm1hYmVsaXhwdWFlbHBpdmp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzQyMjUsImV4cCI6MjA2ODQxMDIyNX0.J0MXaHgZQFu3iFiMhARCYQQYS7KP7iCpiFcRFlqdxRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    // Chrome-specific storage key for better compatibility
    storageKey: 'sb-auth-token'
  }
});